[server]
listen_address = "0.0.0.0:4321"

[api]
url = ""
key = ""
system_prompt = "以下是出现在群聊中的一张图片，请用简练地概括图像内容，尽可能覆盖值得注意的特征。首先给出图片类型，例如：这是一张照片/这是一张表情包/这是一张漫画风格图片/这是一张二次元人物/等等等等，然后开始描述。你只需要进行描述，不要对图像内容做出任何进一步的补充、解释、推断或反馈。"

[api.request_body]
model = ""
max_tokens = 400

[cache]
hash_size = 15
cache_size = 1000
